#pragma once

#define REGISTERS_BASE 0x100

#define INPUT REGISTERS_BASE+0x01
#define INPUT_PULLUP REGISTERS_BASE+0x02
#define INPUT_PULLDOWN REGISTERS_BASE+0x03
#define OUTPUT REGISTERS_BASE+0x04

#define DW1 REGISTERS_BASE+0x05
#define DW0 REGISTERS_BASE+0x06
#define DR REGISTERS_BASE+0x07

#define TBOT REGISTERS_BASE+0x08
#define TBOT_STEPS_PER_UNINT REGISTERS_BASE+0x09
#define TBOT_SETUP REGISTERS_BASE+0x0A
